### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://kodi.weblate.cloud/projects/kodi-add-ons-skins/skin-unity/) for Kodi add-ons: skins/skin.unity.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by gade01 — APPROVED** [review]
Looking very good to me.

**Comment by gade01** [comment]
Would you rather have Weblate PR to Matrix branch?

**Comment by bumpaneer** [comment]
No, master branch is good and I can adjust as needed. That way I won't have to worry about updating the reference in the future.

**Comment by gade01** [comment]
Sounds great, thanks ;)

**Pull request merged**
